plugins: fetchart embedart convert scrub replaygain lastgenre chroma web smartplaylist
directory: /music
# library: /config/musiclibrary.blb
library: /config/musiclibrary.db
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1

paths:
    default: $albumartist/$album%aunique{}/$track - $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title

import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes

replaygain:
    auto: no
    command: mp3gain

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ""

web:
    host: 0.0.0.0
    port: 8337

smartplaylist:
    # relative_to: /music
    playlist_dir: /music
    forward_slash: no
    playlists:
        - name: all.m3u
          query: ""
        - name: "Power-Metal.m3u"
          query:
              [
                  "artist:Disturbed",
                  "artist:Hammerfall",
                  "artist:Gloryhammer",
                  "artist:Battle Beast",
                  "artist:Beast in Black",
              ]
        - name: "Eminem.m3u"
          query: ["artist:Eminem", "artist:Bad meets Evil", "artist:D12"]
        - name: "Daddyphatsnaps.m3u"
          query: "artist:Daddyphatsnaps"
        - name: "Divide-Music.m3u"
          query: "artist:divide music"
        - name: "HMV.m3u"
          query:
              [
                  'title:"my head & my heart"',
                  "title:my head and my heart",
                  "title:telephone",
              ]
        - name: "Genre-Pop.m3u"
          query: "genre:Pop"
        - name: "Genre-Rock.m3u"
          query: "genre:Rock"
        - name: "Genre-Metal.m3u"
          query: "genre:Metal"
        - name: "Genre-KPop.m3u"
          query: "genre:K-Pop"
        - name: "Genre-Electronic.m3u"
          query: "genre:Electro"
        - name: "Genre-Hip-Hop.m3u"
          query: "genre:Hip Hop"
        - name: "Genre-Rap.m3u"
          query: "genre:Rap"
